# pull official base image
FROM python:3.9

RUN apt-get update
RUN mkdir /app
WORKDIR /app
COPY . /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000